//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WPF_DB_DEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public string Name { get; set; }
        public string BloodGrp { get; set; }
        public string City { get; set; }
    }
}
